/* ============================================================
   Self-host the webfonts into /public/fonts and generate
   src/styles/fonts.css. Removes the third-party CDN dependency
   (Fontshare + Google) and the font-flash on load.
   Re-run if weights change:  node scripts/build-fonts.mjs
   ============================================================ */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(__dirname, "..", "public", "fonts");
const stylesDir = join(__dirname, "..", "src", "styles");
mkdirSync(fontsDir, { recursive: true });

const UA = { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/537.36" };
const faces = [];

async function save(url, file) {
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  writeFileSync(join(fontsDir, file), buf);
  return buf.length;
}

// --- Fontshare: Clash Display + Satoshi ---
const fontshare = [
  ["Clash Display", "clash-display", [400, 500, 600, 700]],
  ["Satoshi", "satoshi", [400, 500, 700]],
];
for (const [family, slug, weights] of fontshare) {
  for (const w of weights) {
    const css = await (
      await fetch(`https://api.fontshare.com/v2/css?f%5B%5D=${slug}@${w}&display=swap`, { headers: UA })
    ).text();
    const m = css.match(/url\('(\/\/[^']+\.woff2)'\)/);
    if (!m) throw new Error(`no woff2 for ${slug}@${w}`);
    const file = `${slug}-${w}.woff2`;
    const n = await save("https:" + m[1], file);
    faces.push(
      `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:swap;src:url('/fonts/${file}') format('woff2');}`
    );
    console.log(`  ${file}  ${(n / 1024).toFixed(1)}kb`);
  }
}

// --- Google: IBM Plex Mono (latin subset only — used for ASCII UI labels) ---
const gcss = await (
  await fetch("https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap", { headers: UA })
).text();
const seenWeights = new Set();
for (const block of gcss.split("@font-face").slice(1)) {
  const w = block.match(/font-weight:\s*(\d+)/)?.[1];
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!w || !url || seenWeights.has(w)) continue;
  seenWeights.add(w);
  const file = `ibm-plex-mono-${w}.woff2`;
  const n = await save(url, file);
  faces.push(
    `@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:${w};font-display:swap;src:url('/fonts/${file}') format('woff2');}`
  );
  console.log(`  ${file}  ${(n / 1024).toFixed(1)}kb`);
}

writeFileSync(
  join(stylesDir, "fonts.css"),
  "/* Generated by scripts/build-fonts.mjs — do not edit by hand */\n" + faces.join("\n") + "\n"
);
console.log(`\nWrote ${faces.length} @font-face rules to src/styles/fonts.css`);
